permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      id: set_env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=false /p:TieredCompilation=false --self-contained
    - name: Zip
      run: |
            cp -r bin/Release/net8.0/win-x64/publish/ .
            zip -r release.zip publish/
            md5sum release.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: MonogameBouncingBall.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Please enjoy release ${{ steps.set_env.outputs.RELEASE_VERSION }}"